Add database
KoryRunoMain/java-filmorate pull request #7
Opened 2024-03-24 16:36 UTC by KoryRunoMain

2024-03-24 18:42 UTC, Yang-Pi requested changes

2024-03-24 18:42 UTC, Yang-Pi commented on README.md
Воу, отличное описание проекта!

2024-03-24 18:42 UTC, Yang-Pi commented on .github/workflows/api-tests.yml
Вот это нужно вернуть, потому что иначе у PR нет активных проверок, которые автоматически проверяют код проекта по заданным сценариям

2024-03-24 18:42 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/GenreDaoImpl.java
> +            jdbcTemplate.update(insertQuery, filmId, genre.getId());
Обращение к бд в цикле - это уязвимое место программы с точки зрения приложения, поэтому всегда нужно стремиться к минимизации вызовов одного слоя приложения другим (сервис -> бд). 
В текущем случае можно воспользоваться методом `batchUpdate`
https://www.baeldung.com/spring-jdbc-batch-inserts

2024-03-24 18:42 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/inMemoryStorage/inMemory/InMemoryFilmStorage.java
Тк произошла миграция на бд-хранилище, то реализацию _in memory_ нужно удалить

2024-03-25 11:21 UTC, KoryRunoMain commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/GenreDaoImpl.java
> +            jdbcTemplate.update(insertQuery, filmId, genre.getId());
Спасибо за подсказку!

2024-03-25 21:46 UTC, Yang-Pi approved these changes

2024-03-26 06:30 UTC, merged